# Generated by Django 3.2 on 2023-04-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_username_not_equal_me"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="confirmation_code",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
